[general]
live_config_reload = true

[env]
TERM = "alacritty"
WINIT_UNIX_BACKEND = "wayland"
XKB_DEFAULT_LAYOUT = "ch"

[window]
opacity = 0.6
blur = true
padding = { x = 10, y = 10 }

[font]
size = 10

